### ISSUE TITLE
Hittestresstool not working properly - white page

### ISSUE THREAD

**Issue by lisannewapstra** [nens/hittestresstool-client#32]
Topdesk 2012 0087 Hittestresstool kapot - Joeri verheijden 10 december

### Original ticket

De Hittestresstool lijkt kapot. (Ook gemeld binnen gemeente Utrecht via Margot).

Het issue:
Wanneer je bomen plant en het effect doorrekend kun je vervolgens de voor en na situatie vergelijken. Dit kan je doen door op een locatie de temperatuur op te vragen.
Wanneer ik dit doe lukt het de tool niet om de temperatuur waarden te tonen. Uiteindelijk schiet de browserpagina op een wit scherm.
Kan hier met prio naar gekeken worden?

### Analysis support
Lisanne: I reproduced this. After updating the hittestress and comparing before and after, it suddenly goes to a white screen.
When I open the network tab via F12, I see no error.

@Remco, Can you investigate this? I can show you if you cannot reproduce.

**Comment by lexvand** [comment]
Info from Remco:
> Het gaat om deze file: https://github.com/nens/hittestresstool-client/blob/master/src/utils/api.ts
In regel 29 verwacht hij dat het een array van twee elementen is. Als daar data[0].value staat ipv data[0][1] dan doet hij het weer denk ik.

**Comment by hoanphungt** [comment]
@lexvand 
I merged the PR made by Madeleine and deployed it to staging. Could you test it on staging? Thanks!

**Comment by lexvand** [comment]
Works again on staging.

**Comment by hoanphungt** [comment]
@lexvand 
Should it go to production as well?

**Comment by lexvand** [comment]
@hoanphungt Would be very nice if you could do that, yes.

**Comment by hoanphungt** [comment]
@lexvand 
Deployed to Production

**Comment by lisannewapstra** [comment]
It works again! Thanks for the quick fix.
