### ISSUE TITLE
Testing v2 hittestress tool

### ISSUE THREAD

**Issue by Derryrover** [nens/hittestresstool-client#40]
Now we cannot deploy to staging we need another way to test.

A tester can instead use the local development environment to test the hittestresstool.

Prerequisites:
- a GIT installation
(ipv GIT kun je ook de branch hier downloaden:
https://github.com/nens/hittestresstool-client/tree/tom-imexport_and_pdf_and_infobutton (knop "Code").)
- a npm installation
Google hoe je dit moet doen voor jouw OS of kijk hier: https://www.npmjs.com/get-npm
- a yarn installation
in command line run:
npm install -g yarn

How to test
-Clone the repo here:
https://github.com/nens/hittestresstool-client
-Checkout branch: tom-imexport_and_pdf_and_infobutton
- in the command line run: 
yarn install
- in the commandline run:
PROXY_USERNAME=your.username PROXY_PASSWORD=your.password yarn start

**Comment by Derryrover** [comment]
@wissebeets
@removtilburg

Hi Wisse en Remo,

Nu we niet op staging kunnen testen raad ik jullie aan lokaal te testen.
Zie beschrijving van dit ticket.

Het is beter dat we problemen nu op dev vinden dan later op productie.
Laat me weten als jullie bugs vinden of hulp nodig hebben met testen.

groet Tom

**Comment by RemovTilburg** [comment]
@Derryrover 

Heb je zo tijd om mee te kijken hoe ik dit kan draaien op mijn pc? Of gaan we het morgen op jouw pc laten zien?

**Comment by Derryrover** [comment]
@wissebeets

Hi Wisse,

Ik tag je even in dit ticket omdat dit ticket speciaal is voor het (lokaal ) testen.
Zie ook de "prerequisites" bovenaan in dit ticket.

Als je tijd hebt kun je alvast GIT en NPM installeren.

gr Tom

**Comment by wissebeets** [comment]
Ik heb volgens mij alle benodigde software al, de localhost versie werkte vorige week prima bij mij
