### ISSUE TITLE
Info button 

### ISSUE THREAD

**Issue by Derryrover** [nens/hittestresstool-client#42]
Somewhere there exists a design for a infobutton?

**Comment by Derryrover** [comment]
@removtilburg

Hi Remo,

Ik ben bezig met de infoknop naast de header/title zoals hier in design.
Er bestond toch een .pdf file die moest openen zodra gebruiker hierop klikt?

Zou je die aan dit ticket kunnen attachen (of anders mailen)

groet Tom

**Comment by RemovTilburg** [comment]
Bij deze.

Met vriendelijke groet / Kind regards,

Remo van Tilburg

Adviseur
Nelen & Schuurmans


Werkdagen: ma di wo do vr | Working Days: Mon Tue Wed Thu Fri

+31 (0)30 233 0200   |  +31 (0)6 208 596 47
www.nelen-schuurmans.nl
Zakkendragershof 34-44, 3511AE, Utrecht


[image: Logo N&S]
[image: twitter] <https://twitter.com/nelenschuurmans> [image: linkedin]
<https://www.linkedin.com/company/245070/>


Op do 27 mei 2021 om 11:59 schreef Tom de Boer ***@***.***>:

**Comment by Derryrover** [comment]
work in progress:
https://github.com/nens/hittestresstool-client/pull/44

**Comment by Derryrover** [comment]
This branch:
tom-imexport_and_pdf_and_infobutton

**Comment by Derryrover** [comment]
@removtilburg

Hi Remo,

Ik heropen deze.
Ik weet niet zeker, waarom dit niet werkt. 

groet Tom

**Comment by Derryrover** [comment]
@removtilburg

Hi Remo,

Net een fix gedeployed voor de info button.
Bij mij werkt het correct.
Zou je kunnen testen?

groet Tom

**Comment by RemovTilburg** [comment]
Werkt nu goed :)

Met vriendelijke groet / Kind regards,

Remo van Tilburg

Adviseur
Nelen & Schuurmans


Werkdagen: ma di wo do vr | Working Days: Mon Tue Wed Thu Fri

+31 (0)30 233 0200   |  +31 (0)6 208 596 47
www.nelen-schuurmans.nl
Zakkendragershof 34-44, 3511AE, Utrecht


[image: Logo N&S]
[image: twitter] <https://twitter.com/nelenschuurmans> [image: linkedin]
<https://www.linkedin.com/company/245070/>


Op wo 9 jun. 2021 om 08:41 schreef Tom de Boer ***@***.***>:

**Comment by Derryrover** [comment]
New pdf version:
To be deployed:
https://github.com/nens/hittestresstool-client/releases/tag/0.5.11

**Comment by Derryrover** [comment]
@wissebeests

Hi Wisse,

De nieuwe pdf staat op productie.
Laat me weten als er iets niet klopt.

groet Tom
