### ISSUE TITLE
Hittestress final points

### ISSUE THREAD

**Issue by Derryrover** [nens/hittestresstool-client#45]
- klimaatatlas link naar hittestress. -> Pakt consultant op
- rapport zonder maatregelen. -> Doen we (nog) niet
- importeren geojson autocad. -> Geen actie
- referentiegebied temperatuur. Constante referentie per stad. Configurabel? -> **Dev kan oppakken? Wat zijn de ref waarden?**
- rapport alleen wandelgebieden. -> Geen actie. Klant moet dit zelf doen
- De uitkomst moet voldoende vs onvoldoende zijn? -> Kan dit aan de hand van ref waarden? willen we dit?
- bebouwing toevoegen 
schaduwdoeken -> Doen we nog niet
tool simpel houden / is geen absolute waarheid / gesprek noodzakelijk houden.
idee Wisse: Niet alles in gui, maar wel veel in geojson? -> probleem: is niet zichtbaar in tool dus verwarrend. Ook zichtbaar maken aanpassingen die in tool niet editbaar zijn?
- knoppen minder hoog + whitespace + tools -> **done meer whitespace, maar knoppen minder hoog is meer werk dan verwacht: niet gedaan**

- I can import a polygon for outside my boundingbox. -> doen we nog niet
- boundingbox margins? -> **Dev onderzoeken?**
- detail niveau 2 * sharper WMS -> **Dev onderzoeken?**
-

**Comment by Derryrover** [comment]
@removtilburg
@wissebeets

Hi Remo en Wisse,

Hier een ticet met de door mij gehoorde todo-punten.
Neem ze eens door en ook of mij conclusie na de pijl juist is.

De dikgedrukte kunnen wel/niet opgepakt worden zodra ik een go van jullie krijg.
Voor ieder punt kunnen we een max aantal uren afspreken waarbinnen ik moet blijven, of anders voorlopig opgeven.  (bijv per punt circa 3 uur?)

groet Tom

**Comment by wissebeets** [comment]
Mbt rapportage (PDF), een paar wijzigingen in de tekst:
- in het onderschrift op blz 2 mag deze zin weg: Het voordeel is dat wanneer een van de bronnen geactualiseerd wordt, de PET-hittestresskaart automatisch herberekend wordt met de meest actuele gegevens. De oude kaarten zijn natuurlijk ook nog beschikbaar!
- onder 'verdeling gevoelstemperatuur' mag deze tekst weg: Belangrijk: Er kunnen grote verschillen zitten de verharding van een gebied (denk aan een grote strook groen, maar ook een grote parkeerplaats). Daarom kunnen deze cijfers een vertekend beeld geven
- in het ontwerp van lirry worden kleuren gebruikt in de waarden bij 'huidige situatie 31 graden' en na maatregelen '26,5 graden' dat is wel nice. Idem voor groen vs verhard. Die pie-chart is niet per se nodig, maar die kleurtjes zijn wel leuk. Zie ontwerp lirry in zenhub

**Comment by RemovTilburg** [comment]
@Derryrover 

Ik denk van al die punten de belangrijkste is dat we de lay-out finetunen. Meer zoals Lirry heeft ontworpen: https://xd.adobe.com/view/3a17f620-43ec-4f35-7d44-1c86724075de-4c26/screen/9fb5589c-c141-4369-a311-0a55406a02a3/

Zo zie ik dat er een aantal knoppen niet de correcte naam hebben gekregen zoals Lirry heeft bedacht. De verdeling tussen de knoppen zou ook mooi zijn als dat kan worden meegenomen. Dus die grote whitespace tussen Bomen Planten / Verharding aanpassen en de Upload aanpassingen / Update Hittestress / Exporteer resultaten.

Je geeft aan dat dit meer werk is dan gedacht. Hoeveel uur denk je nodig te hebben om dit aan te passen?

**Comment by Derryrover** [comment]
Ik heb allesbehalve 1 punt hierboven opgepakt in dit pr:
https://github.com/nens/hittestresstool-client/pull/46
Dat is branch tom-imexport_and_pdf_and_infobutton


- [v ] -  in het onderschrift op blz 2 mag deze zin weg: Het voordeel is dat wanneer een van de bronnen geactualiseerd wordt, de PET-hittestresskaart automatisch herberekend wordt met de meest actuele gegevens. De oude kaarten zijn natuurlijk ook nog beschikbaar! --> Done
- [v ] -     onder 'verdeling gevoelstemperatuur' mag deze tekst weg: Belangrijk: Er kunnen grote verschillen zitten de verharding van een gebied (denk aan een grote strook groen, maar ook een grote parkeerplaats). Daarom kunnen deze cijfers een vertekend beeld geven --> Done
- [v ] -     in het ontwerp van lirry worden kleuren gebruikt in de waarden bij 'huidige situatie 31 graden' en na maatregelen '26,5 graden' dat is wel nice. Idem voor groen vs verhard. Die pie-chart is niet per se nodig, maar die kleurtjes zijn wel leuk. Zie ontwerp lirry in zenhub --> Done
- [v ] - Zo zie ik dat er een aantal knoppen niet de correcte naam hebben gekregen zoals Lirry heeft bedacht. -> Done
- [ v] - De verdeling tussen de knoppen zou ook mooi zijn als dat kan worden meegenomen. Dus die grote whitespace tussen Bomen Planten / Verharding aanpassen en de Upload aanpassingen / Update Hittestress / Exporteer resultaten. --> Done
- [] - Bij bovenstaand punt hoort ook impliciet de het smaller/lager maken van de knoppen.
Dit kost dus meer moeite dan gedacht omdat de inhoud van de knoppen oom allemaal kleiner moet worden (ook als deze knop uitklapt).
Minimaal een halve dag.

**Comment by wissebeets** [comment]
Ha Tom, 

Fijn dat je alles al hebt kunnen fixen. Ik zou graag weer even testen vandaag om te kijken hoe belangrijk die smaller/kleiner maken van knoppen is, en om te kijken of de workflow nu lekker is.

Als ik naar mijn lokale kopie http://localhost:3000/hittestresstool ga, krijg ik nu een melding dat die onbereikbaar is. Misschien kun je me even helpen hoe ik dit voor elkaar krijg, ik zet wat in de agenda ok?

**Comment by Derryrover** [comment]
@wissebeets 

Ha Wisse,
Ja schiet maar een meeting in.
Voor zover ik weet werkt localhost:3000 nu alleen op mijn en Remo's computer.
En om het te laten werken moet je de dev server opstarten met yarn start.
We kunnen dit vast en zeker ook op jouw computer wel aan de praat krijgen.

groet Tom

**Comment by wissebeets** [comment]
@Derryrover Ja remo had dat zelfs al bij mij geregeld toen we laatst op kantoor waren. Het werkt nu alleen niet, misschien omdat er een update is, of door de vpn of (waarschijnlijk) door iets anders dat ik niet snap ;)

**Comment by RemovTilburg** [comment]
@Derryrover 

Ha Tom,

Ik zie dat de statistieken nog niet helemaal lekker werken. Volgens mij komt dit doordat er in de zonal api call een celsize van 10 gebruikt wordt. Zou je deze kunnen aanpassen naar 1 ? 

http://localhost:3000/api/v4/rasters/357edce2-b802-46d4-8206-fe1ce9f383eb/zonal/?geom=POLYGON%20((5.118143411356547%2052.09351317170478,%205.118293667933128%2052.09267402196122,%205.11906641604119%2052.092950992580356,%205.118706873518675%2052.09358735903666,%205.118143411356547%2052.09351317170478))&zonal_statistic=mean&**pixel_size=10**&zonal_projection=EPSG:28992

**Comment by Derryrover** [comment]
@RemovTilburg 
Hi Remo, 
Dankje voor de observatie,
Fout verbeterd.

groet Tom

**Comment by wissebeets** [comment]
@Derryrover 
Als je de GeoJSON nu in qgis opent, komt het projectgebied een beetje raar mee.
De bomen en de pavement hebben allebei een duidelijke ID en losse laag, maar het projectgebied niet.
Kun je dit een id geven?
En is het zelfs mogelijk om deze als aparte 'laag' in de geojson te definieren, zodat je dus 3 laagjes krijgt als je 'm laadt?
![image](https://user-images.githubusercontent.com/67963323/120801654-b8dd7780-c541-11eb-9115-c0f9d5652699.png)

**Comment by wissebeets** [comment]
Verder is het wat ons betreft wel echt af allemaal, kunnen we het gaan releasen begin volgende week op productie

**Comment by wissebeets** [comment]
@Derryrover @RemovTilburg 
Wat ons betreft kun je de nieuwe tool alvast live gaan zetten!
Dat maakt het voor ons ook sneller om demo's te geven aan onze (potentiele) klanten.
WAnneer zou je hier aan toe kunnen komen? Liefst al vóór morgen 13:00 als mogelijk

**Comment by Derryrover** [comment]
Old version on prod:
Release 0.5.7
In case prod problem reverse to this one

New version:
0.5.9

**Comment by Derryrover** [comment]
@wissebeets
@removtilburg

Hi Wisse Remo,

Deployen op productie mislukt, omdat er wereldwijde internet problemen zijn. Enkele github services zijn down.
Ik zal het later nogmaals proberen en jullie laten weten.

Aan de GeoJson heb ik een kleine wijziging gedaan. (kun je testen zodra het live is of je kan 'master' branch lokaal uitchecken).
Ik heb wat problemen met de installatie van QGIS op ubuntu en ook de specs https://geojson.org/ geven me geen duidelijkheid over hoe ik features kan groeperen.
Misschien kunnen jullie een voorbeels GeoJSON text file maken van een structuur die voor jullie werkt.

groet Tom

**Comment by Derryrover** [comment]
@removtilburg
@wissebeets
Hi Wisse en Remo,

Deploying to productie is nu gelukt.
Laat me weten als ik nog iets kan doen.

groet Tom

**Comment by RemovTilburg** [comment]
Ha Tom.,

Gaaf!

Ik kom wel een kleine bug tegen als ik op het i'tje klik. Dan opent hij de
tool opnieuw met deze url:
https://demo.lizard.net/hittestresstool/20201211%20-%20Gebruiksaanwijzing%20hittetool.pdf

Met vriendelijke groet / Kind regards,

Remo van Tilburg

Adviseur
Nelen & Schuurmans


Werkdagen: ma di wo do vr | Working Days: Mon Tue Wed Thu Fri

+31 (0)30 233 0200   |  +31 (0)6 208 596 47
www.nelen-schuurmans.nl
Zakkendragershof 34-44, 3511AE, Utrecht


[image: Logo N&S]
[image: twitter] <https://twitter.com/nelenschuurmans> [image: linkedin]
<https://www.linkedin.com/company/245070/>


Op di 8 jun. 2021 om 13:46 schreef Tom de Boer ***@***.***>:
